name: epub_dart
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/0maru/epub_dart

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  xml: ^6.3.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0