name: Lint

on:
  push:

jobs:
  analyze:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pushed commit
        uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - name: Dart Analyze
        run: dart analyze . --fatal-infos
