name: Test

on:
  push:
    paths:
      - "lib/**"
      - "test/**"

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pushed commit
        uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - name: Dart Test
        run: dart test
