name: Test

on:
  push:

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    setps:
      - name: Checkout pushed commit
        uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - name: Dart Test
        run: dart test
