name: Test

on:
  workflow_dispatch:
  push:
    paths:
      - "lib/**"
      - "test/**"

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pushed commit
        uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - name: Dart Test
        run: dart test --coverage=coverage
      - name: Collect coverage
        run: |
          dart pub global activate coverage
          dart pub global run coverage:test_with_coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info
          flags: unittests
          verbose: true
          fail_ci_if_error: true
